export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const LOGUP_SUCCESS = "LOGUP_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ERROR_LOGIN = "ERROR_LOGIN";
export const ERROR_LOGUP = "ERROR_LOGUP";
export const ERROR_UPDATE = "ERROR_UPDATE";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const CATEGORIES = "CATEGORIES";
export const PRODUCT_SHOP = "PRODUCT_SHOP";
export const PAGINATE = "PAGINATE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DECREASE_NUMBER_CART = "DECREASE_NUMBER_CART";
export const INCREASE_NUMBER_CART = "INCREASE_NUMBER_CART";
export const CLEAR_CART = "CLEAR_CART";

export const CREATE_CART = "CREATE_CART"
export const ORDER_CART = "ORDER_CART";
export const UPDATE_CART = "UPDATE_CART";
export const ALL_ORDER = "ALL_ORDER"

export const WIDH_LIST = "WIDH_LIST";
export const REMOVE_FROM_WIDHLIST = "REMOVE_FROM_WIDHLIST";

export const PRODUCT_MODAL = "PRODUCT_MODAL";

export const OPEN_PRODUCT_MODAL = "PRODUCT_MODAL";
export const OPEN_MODAL_CART = "OPEN_MODAL_CART";
export const OPEN_MODAL_SEARCH = "OPEN_MODAL_SEARCH";
export const OPEN_MODAL_SIZE = "OPEN_MODAL_SIZE";
export const CLOSE_MODAL = "CLOSE_MODAL";